---
title: "ACTL6A_growth"
author: "Sunay"
date: '2022-07-19'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(ggsci)
library(tidyverse)
library(reshape2)
library(plotrix)
library(scales)
library(svglite)
```
```{r}
theme_su<-  function(){ 
  font <- "Arial"   #assign font family up front
  
  theme_bw() %+replace%    #replace elements we want to change
    
    theme(
   
      
      #text elements
      plot.title = element_text(             #title
        family = "Arial",            #set font family
        size = 8,                #set font size
        face = 'bold',            #bold typeface
        hjust = 0,                #left align
        vjust = 3),               #raise slightly
      
      plot.subtitle = element_text(          #subtitle
        family = "Arial",            #font family
        size = 6),               #font size
      
      plot.caption = element_text(           #caption
        family = "Arial",            #font family
        size = 6,                 #font size
        hjust = 1),               #right align
      
      axis.title = element_text(             #axis titles
        family = "Arial",
        
        size = 6),               #font size
      
      axis.text = element_text(              #axis text
        family = "Arial",            #axis famuly
        size = 6),                #font size
      
      axis.text.x = element_text(            #margin for axis text
        margin=margin(5, b = 10)),
      
     legend.title=element_text(
       family="Arial",
       size=8,
       hjust = 0),
     legend.text=element_text(
       family = "Arial",
       size=6),
     
     panel.grid.major = element_blank(),
     panel.grid.minor = element_blank()
     )
  
     
    
}



```


```{r}
actl_growth<- read.csv2(file = "input/actl_growth.txt", sep="\t")

a<-melt(actl_growth, id=1)


a$value<- as.numeric(a$value)

b<- a %>% separate(variable, into = c("X", "Distance"),sep = "X")
b<- b%>% separate(Distance, into = c("Distance","X"), sep="_")

b<-b %>% select(1:3)
names(b)<- c("Time", "Ratio" ,"Distance")
c<-b %>%  group_by(Distance, Time) %>% summarise(across(
    .cols = where(is.numeric), 
    .fns = list(Mean = mean, SD = std.error), na.rm = TRUE, 
    .names = "{col}_{fn}"
  )) %>% droplevels()

c<- c %>% filter(Time< 22 | Time >28)

su_palette<-   c("#0700C4","#0000FF","#0052FF","#007AFF","#00A3FF","#00CCFF")
  
  
actl_plot<- c %>% ggplot(aes(x=Time, y=Ratio_Mean, color=Distance))+geom_line()+geom_point()+geom_errorbar(aes(ymin=Ratio_Mean-Ratio_SD, ymax=Ratio_Mean+Ratio_SD), width=0.3)+xlim(16,50)+theme_su()+ggtitle("Growth Effect of \nACTL6A Targeting Guides")+xlab("Time (h)")+ylab("Ratio to time=0")+scale_color_manual(name="Distance to\nACTL6A  TSS (bp)", limits = c("26", "33", "615", "812", "951", "1069"), values = su_palette)+ylim(1.9,6.3)
actl_plot





```

