---
title: "CRISPRi_comparison_with_other_screens"
author: "Sunay"
date: "10/15/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("E:/Paper writing/CRIPSRi paper/Analyses/CRISPR-CRISPRi_Comparison/pub_final")
```

```{r}
library(tidyverse)
library(ggpubr)
library(ggrepel)
library(ggsci)
library(svglite)
```

```{r}
theme_su<-  function(){ 
  font <- "Arial"   #assign font family up front
  
  theme_bw() %+replace%    #replace elements we want to change
    
    theme(
   
      
      #text elements
      plot.title = element_text(             #title
        family = "Arial",            #set font family
        size = 8,                #set font size
        face = 'bold',            #bold typeface
        hjust = 0,                #left align
        vjust = 3),               #raise slightly
      
      plot.subtitle = element_text(          #subtitle
        family = "Arial",            #font family
        size = 6),               #font size
      
      plot.caption = element_text(           #caption
        family = "Arial",            #font family
        size = 6,                 #font size
        hjust = 1),               #right align
      
      axis.title = element_text(             #axis titles
        family = "Arial",
        
        size = 6),               #font size
      
      axis.text = element_text(              #axis text
        family = "Arial",            #axis famuly
        size = 6),                #font size
      
      axis.text.x = element_text(            #margin for axis text
        margin=margin(5, b = 10)),
      
     legend.title=element_text(
       family="Arial",
       size=8,
       hjust = 0),
     legend.text=element_text(
       family = "Arial",
       size=6),
     
     panel.grid.major = element_blank(),
     panel.grid.minor = element_blank()
     )
  
     
    
}
```


```{r}
### import lfc from ihyr data
ihyr_data <- read.delim("input/ihyr_data.txt")

names(ihyr_data)
levels(ihyr_data$comparison_name)
ihyr<- ihyr_data %>% subset(comparison_name=="Dox_Day_18-No_Dox_Day_0")
summary(ihyr)
ihyr %>% filter(symbol=="BRCA1")
ihyr_gene_lvl<- ihyr %>%
  group_by(symbol) %>%
  summarise_at(vars(Log2FoldChange), funs(mean(., na.rm=TRUE)))

ihyr_gene_lvl<- ihyr_gene_lvl %>% rename(Gene=symbol)

merged_annotated<-read.csv(file = "input/merged_annotated.txt")

names(merged_annotated)

screen_data<- merged_annotated %>% select(Gene, Annot,IPSC_AV_inh, IPSC_Av_Cut, K562_Av_inh, K562_Av_cut)

names(ihyr_gene_lvl)<- c("Gene", "IHRY")

screen_data<- inner_join(ihyr_gene_lvl, screen_data, by="Gene")

yilmaz <- read.delim("input/yilmaz.txt")
names(yilmaz)

yilmaz<- yilmaz  %>% rename(Gene="Gene.Symbol", yilmaz="CRISPR.score")
screen_data<- inner_join(yilmaz, screen_data, by="Gene")

summary(screen_data)
```

###Plots
## inh vs ihry
```{r}


inh_vs_ihry<- ggplot()+
  geom_point(data=(screen_data %>% filter(Annot=="Other")),aes(x=IHRY, y=IPSC_AV_inh, color=Annot), size=0.05, alpha=0.5)+
  geom_point(data=(screen_data %>% filter(Annot=="NEG")),aes(x=IHRY, y=IPSC_AV_inh,color=Annot), size=0.05, alpha=0.5)+
  geom_point(data=(screen_data%>% filter(Annot=="CEG")),aes(x=IHRY, y=IPSC_AV_inh,color=Annot), size=0.05, alpha=0.5)+
  
  stat_cor(data=screen_data, inherit.aes = F, aes(x=IHRY, y=IPSC_AV_inh,label = ..r.label..), method = "pearson", size=2)+
  ggtitle("Ihry et al vs CRISPRi")+
  labs(x="Ihyr et al", y="CRISPRi")+
  theme_su()+
  scale_color_nejm(name="Gene Function",                                                          labels=c("CEG"="Core Essential Genes" , "NEG"="Non-Essential Genes", "Other"="Other Genes"))
```

## inh vs cut
```{r}
inh_vs_cut<-
ggplot()+
  geom_point(data=(screen_data %>% filter(Annot=="Other")),aes(x=IPSC_Av_Cut, y=IPSC_AV_inh, color=Annot), size=0.05, alpha=0.5)+
  geom_point(data=(screen_data %>% filter(Annot=="NEG")),aes(x=IPSC_Av_Cut, y=IPSC_AV_inh,color=Annot), size=0.05, alpha=0.5)+
  geom_point(data=(screen_data%>% filter(Annot=="CEG")),aes(x=IPSC_Av_Cut, y=IPSC_AV_inh,color=Annot), size=0.05, alpha=0.5)+
  
  stat_cor(data=screen_data, inherit.aes = F, aes(x=IPSC_Av_Cut, y=IPSC_AV_inh,label = ..r.label..), method = "pearson", size=2)+
  ggtitle("CRISPR vs CRISPRi data")+
  labs(x="CRISPR", y="CRISPRi")+
  theme_su()+
  scale_color_nejm(name="Gene Function",                                                          labels=c("CEG"="Core Essential Genes" , "NEG"="Non-Essential Genes", "Other"="Other Genes"))
```

## inh vs yilmaz
```{r}
screen_data$yilmaz

inh_vs_yilmaz<-
ggplot()+
  geom_point(data=(screen_data %>% filter(Annot=="Other")),aes(x=yilmaz, y=IPSC_AV_inh, color=Annot), size=0.05, alpha=0.5)+
  geom_point(data=(screen_data %>% filter(Annot=="NEG")),aes(x=yilmaz, y=IPSC_AV_inh,color=Annot), size=0.05, alpha=0.5)+
  geom_point(data=(screen_data%>% filter(Annot=="CEG")),aes(x=yilmaz, y=IPSC_AV_inh,color=Annot), size=0.05, alpha=0.5)+
  
  stat_cor(data=screen_data, inherit.aes = F, aes(x=yilmaz, y=IPSC_AV_inh,label = ..r.label..), method = "pearson", size=2)+
  ggtitle("Yilmaz et al vs CRISPRi data")+
  labs(x="Yilmaz et al", y="CRISPRi")+
  theme_su()+
  scale_color_nejm(name="Gene Function",                                                          labels=c("CEG"="Core Essential Genes" , "NEG"="Non-Essential Genes", "Other"="Other Genes"))
```

## cut vs yilmaz
```{r}
cut_vs_yilmaz<-
ggplot()+
  geom_point(data=(screen_data %>% filter(Annot=="Other")),aes(x=yilmaz, y=IPSC_Av_Cut, color=Annot), size=0.05, alpha=0.5)+
  geom_point(data=(screen_data %>% filter(Annot=="NEG")),aes(x=yilmaz, y=IPSC_Av_Cut,color=Annot), size=0.05, alpha=0.5)+
  geom_point(data=(screen_data%>% filter(Annot=="CEG")),aes(x=yilmaz, y=IPSC_Av_Cut,color=Annot), size=0.05, alpha=0.5)+
  
  stat_cor(data=screen_data, inherit.aes = F, aes(x=yilmaz, y=IPSC_Av_Cut,label = ..r.label..), method = "pearson", size=2)+
  ggtitle("Yilmaz et al vs CRISPR data")+
  labs(x="Yilmaz et al", y="CRISPR")+
  theme_su()+
  scale_color_nejm(name="Gene Function",                                                          labels=c("CEG"="Core Essential Genes" , "NEG"="Non-Essential Genes", "Other"="Other Genes"))

cut_vs_yilmaz
```

## cut vs ihry

```{r}

cut_vs_ihry<-
ggplot()+
  geom_point(data=(screen_data %>% filter(Annot=="Other")),aes(x=IHRY, y=IPSC_Av_Cut, color=Annot), size=0.05, alpha=0.5)+
  geom_point(data=(screen_data %>% filter(Annot=="NEG")),aes(x=IHRY, y=IPSC_Av_Cut,color=Annot), size=0.05, alpha=0.5)+
  geom_point(data=(screen_data%>% filter(Annot=="CEG")),aes(x=IHRY, y=IPSC_Av_Cut,color=Annot), size=0.05, alpha=0.5)+
  
  stat_cor(data=screen_data, inherit.aes = F, aes(x=IHRY, y=IPSC_Av_Cut,label = ..r.label..), method = "pearson", size=2)+
  ggtitle("Ihry et al vs CRISPR data")+
  labs(x="Ihry et al", y="CRISPR")+
  theme_su()+
  scale_color_nejm(name="Gene Function",                                                          labels=c("CEG"="Core Essential Genes" , "NEG"="Non-Essential Genes", "Other"="Other Genes"))

cut_vs_ihry

```

## ihry vs yilmaz
```{r}


yilmaz_vs_ihry<-
ggplot()+
  geom_point(data=(screen_data %>% filter(Annot=="Other")),aes(x=IHRY, y=yilmaz, color=Annot), size=0.05, alpha=0.5)+
  geom_point(data=(screen_data %>% filter(Annot=="NEG")),aes(x=IHRY, y=yilmaz,color=Annot), size=0.05, alpha=0.5)+
  geom_point(data=(screen_data%>% filter(Annot=="CEG")),aes(x=IHRY, y=yilmaz,color=Annot), size=0.05, alpha=0.5)+
  
  stat_cor(data=screen_data, inherit.aes = F, aes(x=IHRY, y=yilmaz,label = ..r.label..), method = "pearson", size=2)+
  ggtitle("Ihry et al vs Yilmaz et al Data")+
  labs(x="Ihry et al", y="Yilmaz et al")+
  theme_su()+
  scale_color_nejm(name="Gene Function",                                                          labels=c("CEG"="Core Essential Genes" , "NEG"="Non-Essential Genes", "Other"="Other Genes"))

yilmaz_vs_ihry


```

```{r}


fig_4_h<- ggarrange(inh_vs_cut,
          inh_vs_ihry,
          inh_vs_yilmaz,
          cut_vs_ihry,
          cut_vs_yilmaz,
          yilmaz_vs_ihry,
   common.legend = T, legend = "bottom") 
fig_4_h<- annotate_figure(fig_4_h, top=text_grob("Comparison of Screens in Stem Cells", size = 8))
fig_4_h
ggsave(fig_4_h, filename = "E:/Paper writing/CRIPSRi paper/Analyses/plots/panel_4/fig_4_h.svg", width = 6, height = 5, dpi=1000)

```

###end of analysis